### ISSUE TITLE
Source for the fonts?

### ISSUE THREAD

**Issue by Tachidevt** [Niosa/D012FFRT#2]
The project does not seem to have the source fonts added to the repo, which makes continuing the project difficult. It seems you edited the original fonts (at least some of them) some way? Are they fonts used in the .psd files still preserved?

**Comment by Niosa** [comment]
I'm away from home right now, but as soon as I'm able I'll get that font added here. I did edit some of them in PS, but you'd probably still need the original font file. I'll follow up on that ASAP.

**Comment by Tachidevt** [comment]
Thank you very, very much! Have a great vacation if you're on one.
