### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by yawOuch** [Niosa/D012FFRT#4]
Hi need help with the path you mention. In my unit laptop, there is no path PPSSPP\memstick\PSP\TEXTURES\ULUS10566. Do I need to create this path?

**Comment by yawOuch** [comment]
@Niosa

**Comment by stonerlunchbox024** [comment]
@yawOuch That's what I did and it's working for me

**Comment by Niosa** [comment]
> Hi need help with the path you mention. In my unit laptop, there is no path PPSSPP\memstick\PSP\TEXTURES\ULUS10566. Do I need to create this path?

If the path doesn't already exist, yes. Also, that path is for the US version.
